# Generated by Django 4.2.16 on 2025-12-02 21:45

import apps.core.utils.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_id', models.CharField(db_index=True, max_length=32, unique=True, validators=[apps.core.utils.validators.validate_device_id])),
                ('name', models.CharField(max_length=100)),
                ('device_type', models.CharField(choices=[('LITE', 'SmartLock LITE'), ('PRO', 'SmartLock PRO')], default='LITE', max_length=10)),
                ('device_secret', models.CharField(max_length=64, unique=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('MAINTENANCE', 'Maintenance')], default='ACTIVE', max_length=20)),
                ('is_locked', models.BooleanField(default=True)),
                ('is_online', models.BooleanField(default=False)),
                ('battery_level', models.IntegerField(default=100)),
                ('battery_low_threshold', models.IntegerField(default=20)),
                ('keypad_enabled', models.BooleanField(default=False)),
                ('nfc_enabled', models.BooleanField(default=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('last_unlock', models.DateTimeField(blank=True, null=True)),
                ('last_lock', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Device',
                'verbose_name_plural': 'Devices',
                'db_table': 'devices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('UNLOCK', 'Unlock'), ('LOCK', 'Lock'), ('UNLOCK_APP', 'Unlock via App'), ('UNLOCK_NFC', 'Unlock via NFC'), ('UNLOCK_PIN', 'Unlock via PIN'), ('UNLOCK_PHYSICAL', 'Unlock via Physical Key'), ('BATTERY_LOW', 'Battery Low'), ('DEVICE_ONLINE', 'Device Online'), ('DEVICE_OFFLINE', 'Device Offline'), ('TAMPER_DETECTED', 'Tamper Detected')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Device Log',
                'verbose_name_plural': 'Device Logs',
                'db_table': 'device_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceSharing',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('OWNER', 'Owner'), ('ADMIN', 'Admin'), ('MEMBER', 'Member'), ('VIEWER', 'Viewer')], default='MEMBER', max_length=10)),
                ('can_unlock', models.BooleanField(default=True)),
                ('can_lock', models.BooleanField(default=True)),
                ('can_view_logs', models.BooleanField(default=True)),
                ('can_manage_access', models.BooleanField(default=False)),
                ('can_share', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_with', to='devices.device')),
            ],
            options={
                'verbose_name': 'Device Sharing',
                'verbose_name_plural': 'Device Sharings',
                'db_table': 'device_sharing',
                'ordering': ['-created_at'],
            },
        ),
    ]
