# Generated by Django 4.2.16 on 2025-12-02 21:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicesharing',
            name='shared_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices_shared_by_me', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='devicesharing',
            name='shared_with',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_devices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='devicelog',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='devices.device'),
        ),
        migrations.AddField(
            model_name='devicelog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='device',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='devicesharing',
            unique_together={('device', 'shared_with')},
        ),
        migrations.AddIndex(
            model_name='devicelog',
            index=models.Index(fields=['device', '-created_at'], name='device_logs_device__15f61f_idx'),
        ),
        migrations.AddIndex(
            model_name='devicelog',
            index=models.Index(fields=['event_type', '-created_at'], name='device_logs_event_t_e26126_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['owner', 'status'], name='devices_owner_i_6afdf0_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['device_id'], name='devices_device__c4b5e4_idx'),
        ),
    ]
