# Generated by Django 4.2.16 on 2025-12-02 21:45

import apps.core.utils.validators
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GuestAccess',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('guest_name', models.CharField(max_length=100)),
                ('guest_email', models.EmailField(blank=True, max_length=254)),
                ('guest_phone', models.CharField(blank=True, max_length=20)),
                ('access_type', models.CharField(choices=[('NFC', 'NFC Card'), ('PIN', 'PIN Code')], max_length=10)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Guest Access',
                'verbose_name_plural': 'Guest Access',
                'db_table': 'guest_access',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NFCCard',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uid', models.CharField(help_text='NFC UID (e.g., 04:A3:2F:B2)', max_length=23, unique=True, validators=[apps.core.utils.validators.validate_nfc_uid])),
                ('name', models.CharField(help_text='Card name/label', max_length=100)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('usage_count', models.IntegerField(default=0)),
                ('max_usage', models.IntegerField(blank=True, help_text='Maximum usage count (null = unlimited)', null=True)),
                ('allowed_days', models.JSONField(blank=True, default=list, help_text='Allowed days: ["mon","tue","wed","thu","fri","sat","sun"]')),
                ('allowed_hours', models.JSONField(blank=True, default=dict, help_text='Allowed hours: {"start":"08:00","end":"18:00"}')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'NFC Card',
                'verbose_name_plural': 'NFC Cards',
                'db_table': 'nfc_cards',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PINCode',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pin_hash', models.CharField(max_length=64)),
                ('name', models.CharField(help_text='PIN name/label', max_length=100)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('usage_count', models.IntegerField(default=0)),
                ('max_usage', models.IntegerField(blank=True, help_text='Maximum usage count (null = unlimited)', null=True)),
                ('allowed_days', models.JSONField(blank=True, default=list)),
                ('allowed_hours', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'PIN Code',
                'verbose_name_plural': 'PIN Codes',
                'db_table': 'pin_codes',
                'ordering': ['-created_at'],
            },
        ),
    ]
