# Generated by Django 4.2.16 on 2025-12-02 21:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('devices', '0001_initial'),
        ('access', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pincode',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pin_codes_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pincode',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pin_codes', to='devices.device'),
        ),
        migrations.AddField(
            model_name='pincode',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pin_codes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nfccard',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nfc_cards_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nfccard',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nfc_cards', to='devices.device'),
        ),
        migrations.AddField(
            model_name='nfccard',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nfc_cards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='guestaccess',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_access_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='guestaccess',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_access', to='devices.device'),
        ),
        migrations.AddField(
            model_name='guestaccess',
            name='nfc_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guest_access', to='access.nfccard'),
        ),
        migrations.AddField(
            model_name='guestaccess',
            name='pin_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guest_access', to='access.pincode'),
        ),
        migrations.AddIndex(
            model_name='pincode',
            index=models.Index(fields=['device', 'is_active'], name='pin_codes_device__734914_idx'),
        ),
        migrations.AddIndex(
            model_name='nfccard',
            index=models.Index(fields=['device', 'is_active'], name='nfc_cards_device__f3d541_idx'),
        ),
        migrations.AddIndex(
            model_name='nfccard',
            index=models.Index(fields=['uid'], name='nfc_cards_uid_e6178d_idx'),
        ),
    ]
